/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch design system colors
        'primary':                    '#361f1a',
        'on-primary':                 '#ffffff',
        'primary-container':          '#4e342e',
        'on-primary-container':       '#c19c94',
        'primary-fixed':              '#ffdad2',
        'primary-fixed-dim':          '#e5beb5',
        'on-primary-fixed':           '#2b1611',
        'on-primary-fixed-variant':   '#5c403a',
        'secondary':                  '#7e5700',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#feb300',
        'on-secondary-container':     '#6a4800',
        'secondary-fixed':            '#ffdeac',
        'secondary-fixed-dim':        '#ffba38',
        'on-secondary-fixed':         '#281900',
        'on-secondary-fixed-variant': '#604100',
        'tertiary':                   '#002c06',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#00450d',
        'on-tertiary-container':      '#66b664',
        'tertiary-fixed':             '#a3f69c',
        'tertiary-fixed-dim':         '#88d982',
        'on-tertiary-fixed':          '#002204',
        'on-tertiary-fixed-variant':  '#005312',
        'surface':                    '#fff9ea',
        'surface-dim':                '#e0dac4',
        'surface-bright':             '#fff9ea',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#faf4dd',
        'surface-container':          '#f5eed7',
        'surface-container-high':     '#efe8d2',
        'surface-container-highest':  '#e9e2cc',
        'surface-variant':            '#e9e2cc',
        'surface-tint':               '#755750',
        'on-surface':                 '#1e1c0e',
        'on-surface-variant':         '#504442',
        'outline':                    '#827471',
        'outline-variant':            '#d4c3bf',
        'background':                 '#fff9ea',
        'on-background':              '#1e1c0e',
        'inverse-surface':            '#333121',
        'inverse-on-surface':         '#f8f1da',
        'inverse-primary':            '#e5beb5',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
      },
      fontFamily: {
        display: ['var(--font-jakarta)', 'Plus Jakarta Sans', 'sans-serif'],
        sans:    ['var(--font-vietnam)', 'Be Vietnam Pro', 'sans-serif'],
      },
      animation: {
        'heart-pop': 'heartPop 0.35s ease',
        'fade-in':   'fadeIn 0.2s ease',
        'slide-up':  'slideUp 0.25s ease',
        'pulse-slow':'pulseSlow 3s ease-in-out infinite',
      },
      keyframes: {
        heartPop: {
          '0%':   { transform: 'scale(1)' },
          '50%':  { transform: 'scale(1.4)' },
          '100%': { transform: 'scale(1)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSlow: {
          '0%, 100%': { opacity: '0.2' },
          '50%':      { opacity: '0.4' },
        },
      },
    },
  },
  plugins: [],
};
